access/urls.py
from django.urls import path, include
from rest_framework import routers


from .views import EndPointViewset

webhookrouter = routers.DefaultRouter()

webhookrouter.register(r'webhook', EndPointViewset)

urlpatterns = [
    path("/api/V1.0/wa/weebhook", EndPointViewset.as_view(), name="webhook")
]

whatsapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from api.views import render_agenda, agenda_pdf, home, discursante_pdf, oracion_pdf
from access.views import EndPointViewset

urlpatterns = [
    path('admin/', admin.site.urls),
    path('<int:pk>/', render_agenda, name="agenda"),
    path('agenda-pdf/<int:pk>/', agenda_pdf, name="descargaPDF"),
    path('discurso/<int:pk>/', discursante_pdf, name="discurso"),
    path('oracion/<int:pk>/', oracion_pdf, name="oracion"),
    path('', home, name="home"),
    path('api/V1.0/wa/webhoook/', EndPointViewset.as_view(), name="webhook"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/models.py
from django.db import models
from .opciones import LLAMAMIENTOS, LISTA_HIMNOS, TIPO_HIMNO, TIPO_ORACION


# Create your models here.

class Obispado(models.Model):
	nombre = models.CharField(max_length=50)
	llamamiento = models.CharField(choices=LLAMAMIENTOS, max_length=2)
	class Meta(object):
		verbose_name_plural = "Obispado"
	def __str__(self):
		return f"{LLAMAMIENTOS[self.llamamiento]} - {self.nombre}"
	

class Organizacion(models.Model):
	nombre = models.CharField(max_length=50)
	nombre_corto = models.CharField(max_length=10)
	codigo = models.CharField(max_length=15)
	class Meta(object):
		verbose_name_plural = "Organizaciones"
	
	def __str__(self):
		return self.nombre
	

class Agenda(models.Model):
	fecha = models.DateField(auto_now=False, auto_now_add=False)
	primer_domingo = models.BooleanField(default=False)
	dirige = models.ForeignKey(Obispado, models.SET_NULL, blank=True, null=True, related_name="dirige")
	preside = models.ForeignKey(Obispado, models.SET_NULL, blank=True, null=True, related_name="preside")
	piano = models.CharField(max_length=50, default="Jose Galicia")
	direccion_himnos = models.CharField(max_length=50, default="Alma Aceituno")
	def __str__(self):
		return str(self.fecha)

class Templo(models.Model):
	fecha = models.DateTimeField(auto_now=False, auto_now_add=False)
	reservado_por = models.ForeignKey(Obispado, models.SET_NULL, blank=True, null=True)
	reserva_confirmada = models.BooleanField(default=False)
	observaciones = models.TextField(blank=True)
	agenda = models.ManyToManyField(Agenda, blank=True)

	class Meta(object):
		verbose_name_plural = "Templo"

	def __str__(self):
		return str(self.fecha.strftime("%d/%m/%Y - %I:%M%p"))

class Entrevista(models.Model):
	nombre = models.CharField(max_length=50)
	fecha = models.DateTimeField(auto_now=False, auto_now_add=False)
	quien_realiza = models.ForeignKey(Obispado, models.SET_NULL, blank=True, null=True)
	def __str__(self):
		return self.nombre

class Himno(models.Model):
	numero = models.CharField(choices=LISTA_HIMNOS, max_length=50)
	tipo = models.CharField(choices=TIPO_HIMNO, max_length=3)
	agenda = models.ForeignKey(Agenda, on_delete=models.CASCADE, blank=True, null=True)

	def __str__(self):
		return self.numero

class Limpieza(models.Model):
	fecha = models.DateField(auto_now=False, auto_now_add=False)
	organizacion = models.ForeignKey(Organizacion, models.SET_NULL, blank=False, null=True)
	finalizada = models.BooleanField()
	agenda = models.ForeignKey(Agenda, on_delete=models.CASCADE, blank=True, null=True)
	class Meta(object):
		verbose_name_plural = "Limpieza"
	
	def __str__(self):
		return f"{self.fecha.strftime('%d/%m/%Y')} - {self.organizacion}"


class Miembro(models.Model):
	nombre = models.CharField(max_length=75)
	def __str__(self):
		return self.nombre


class Oracion(models.Model):
	nombre = models.ForeignKey(Miembro, on_delete=models.CASCADE, null=True)
	tipo = models.CharField(choices=TIPO_ORACION, max_length=10, blank=True)
	confirmado = models.BooleanField(default=False)
	agenda = models.ForeignKey(Agenda, on_delete=models.CASCADE, blank=True, null=True)
	def __str__(self):
		return f"{self.agenda} - {self.nombre}"
	

class Asunto(models.Model):
	organizacion = models.ForeignKey(Organizacion, models.SET_NULL, blank=True, null=True)
	titulo = models.CharField(max_length=50)
	descripcion = models.TextField(blank=True)
	fecha = models.DateField(auto_now=False, auto_now_add=False)
	encargado = models.ForeignKey(Obispado, models.SET_NULL, blank=True, null=True)
	agenda = models.ManyToManyField(Agenda, blank=True)
	def __str__(self):
		return	f"{self.fecha.strftime('%d/%m/%Y')} {self.titulo} - {self.organizacion}"

class Actividad(models.Model):
	organizacion = models.ForeignKey(Organizacion, models.SET_NULL, blank=False, null=True)
	titulo = models.CharField(max_length=50)
	descripcion = models.TextField()
	lugar = models.CharField(max_length=100)
	fecha = models.DateTimeField(auto_now=False, auto_now_add=False)
	presupuesto = models.BooleanField(default=False)
	aprobado = models.BooleanField(default=False)
	agenda = models.ManyToManyField(Agenda, blank=True)
	class Meta(object):
		verbose_name_plural = "Actividades"
	def __str__(self):
		return	f"{self.fecha.strftime('%d/%m/%Y %I:%M %p')} {self.titulo} - {self.organizacion}"
	


class Discurso(models.Model):
	nombre = models.ForeignKey(Miembro, on_delete=models.CASCADE, null=True)
	tema = models.CharField(max_length=50)
	cofirmado = models.BooleanField(default=False)
	agenda = models.ForeignKey(Agenda, on_delete=models.CASCADE, blank=True, null=True)
	def __str__(self):
		return	f"{self.nombre.nombre} - {self.tema}"

api/views.py
from django.shortcuts import render, HttpResponse
from django.template.loader import get_template
from .models import Agenda, Discurso, Oracion, Actividad

# Create your views here.

def render_agenda(request, pk):
    try:
        agenda = Agenda.objects.get(pk=pk)
        return render(request, "api/agenda.html", {"agenda": agenda})
    except Agenda.DoesNotExist:
        return render(request, "api/agenda.html")

def home(request):
    try:
        actividad = Actividad.objects.all()
        return render(request, "api/home.html", {"actividad": actividad})
    except:
        return render(request, "api/home.html")

    
def agenda_pdf(request, pk):

    agenda = Agenda.objects.get(pk=pk)
    template = get_template("api/agenda.html")
    context = {"agenda": agenda}
    html = template.render(context)
    
    return HttpResponse(html)

def discursante_pdf(request, pk):
    discursante = Discurso.objects.get(pk=pk)

    template= get_template("api/discurso.html")
    context = {"discursante": discursante}
    html = template.render(context)

    return HttpResponse(html)

def oracion_pdf(request, pk):
    oracion = Oracion.objects.get(pk=pk)

    template = get_template("api/oracion.html")
    context = {"oracion": oracion}
    html = template.render(context)

    return HttpResponse(html)

api/templates/api/agenda.html
{% load utils %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Agenda {{agenda.fecha}}</title>
  <style>
    :root {
      --header: 1.60em;
      --sub_header: 1.27em;
      --text: 1.10em;
    }

    header {
      display: flex;
      flex-direction: column;
      width: 100%;
    }

    header > h2, header > h3 {
      margin: 0 auto;
    }
    
    p, p * {
      font-size: var(--text)
    }

    header > section {
      display: flex;
      flex-direction: row;
      justify-content: end;
    }

    footer > img {
      display: block;
      margin: 0 auto;
      margin-top: 3em;
      height: 150px;
    }
    .divider {
      border-bottom: 1px solid black;
      display: block;
      height: 1em;
      flex: 1;
    }

    .fw {
      width: 100%;
    }

    main {
      max-width: 100%;
    }

    main > p {
      display: flex;
      height: 1.5em;
    }

    .testimonios {
      columns: 3;
      word-break: break-all;
      line-height: 40px;
      width: auto;
      column-gap: 1.5em 1.5em;
    }

    ul {
      list-style-type: none;
      margin-block-start: 0;
    }

    li.with-bullet:before {
      content: "\25A1";
      font-size: 2em;
      margin-right: 0.5em;
    }

    .controls {
      display: flex;
      width: 100%;
      align-items: center;
      justify-content: space-between;
    }

    @page {
      @bottom {
        content: counter(page);
      }
    }

    @media print {
      .controls {
        display: none;
      }
    }

  </style>

</head>
<body onLoad="">
  {% if agenda %}
  <div class="controls">
    <label for="font_size">
      Tamaño de fuente
      <select name="font_size" id="font_size">
        <option value="default">Normal</option>
        <option value="medium" selected>Mediano</option>
        <option value="large">Grande</option>
      </select>
    </label>
    <button onClick="print()">Imprimir</button>
  </div>
    <header>
      <h2>Reunion Sacramental</h2>
      <h3>Barrio Pinares 1</h3>
      <br /><br />
      <section>{{agenda.fecha}}</section>
    </header>
    <main>
      <p><strong>Bienvenida:&nbsp;</strong>A todos los presentes; <span class="divider"> </span></p>
      <p><strong>Preside:&nbsp;</strong>{{agenda.preside.get_llamamiento_display}} {{agenda.preside.nombre}}</p>
      <p><strong>Dirige:&nbsp;</strong>{{agenda.dirige.get_llamamiento_display}} {{agenda.dirige.nombre}}</p>
      <p><strong>Piano:&nbsp;</strong> {{agenda.piano}}</p>
      <p><strong>Direccion de los himnos:&nbsp;</strong> {{agenda.direccion_himnos}}</p>
      <p><strong>Reconocimento de lideres:&nbsp;</strong><span class="divider"></span></p>
      <p><span class="divider"></span></p>
      <p><strong>Primer Himno:&nbsp;</strong> {{agenda.himno_set.values| himno:'1er'}}</p>
      <p><strong>Primera oracion:&nbsp;</strong>  {{agenda.oracion_set.values|oracion:'primera'}}</p>
      {% if agenda.asunto_set.values|length > 0 %}
        <p><strong>Asuntos de barrio</strong></p>
        <ul>
          {% for asunto in agenda.asunto_set.all  %}
            <li class="with-bullet"><strong>{{asunto.titulo}}</strong> - {{asunto.descripcion}}</li>
          {% endfor %}
          <p><span class="divider"></span></p>
          <p><span class="divider"></span></p>
        </ul>
      {% endif %}
      <p><strong>Asuntos de estaca</strong></p>
      <p><strong>Tiempo para bendecir la santa cena</strong></p>
      <p><strong>Himno sacramental:&nbsp;</strong> {{agenda.himno_set.values | himno:'2do'}}</p>
      {% if agenda.primer_domingo %}
        <p style="page-break-before: always;"><strong>Testimonios</strong></p>  
        <div class="testimonios">
          ________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________
        </div>
      {% else %}
        <p><strong>Discursantes</strong></p>
        <p><strong>Primer discursante:&nbsp;</strong> {{agenda.discurso_set.values.0.nombre_id | discursante}}</p>
        <p><strong>Himno intermedio:&nbsp;</strong> {{agenda.himno_set.values | himno:'3er'}}</p>
        <p><strong>Agradecimiento especial a todos los hermanos y hermanas que hacen posible esta reunion</strong></p>
        <p><strong>Segundo discursante:&nbsp;</strong> {{agenda.discurso_set.values.1.nombre_id | discursante }}</p>
        {% if agenda.discurso_set.values.2.nombre_id %}
          <p><strong>Tercer discursante:&nbsp;</strong> {{agenda.discurso_set.values.2.nombre_id | discursante }}</p>
        {% endif %}
        {% if agenda.discurso_set.values.3.nombre_id %}
          <p><strong>Cuarto discursante:&nbsp;</strong> {{agenda.discurso_set.values.3.nombre_id | discursante }}</p>
        {% endif %}
        {% if agenda.discurso_set.values.4.nombre_id %}
          <p><strong>Quinto discursante:&nbsp;</strong> {{agenda.discurso_set.values.4.nombre_id | discursante }}</p>
        {% endif %}
          {% if agenda.discurso_set.values.5.nombre_id %}
            <p><strong>Quinto discursante:&nbsp;</strong> {{agenda.discurso_set.values.5.nombre_id | discursante }}</p>
          {% endif %}
        {% endif %}
        <p><strong>Ultimo Himno:&nbsp;</strong> {{agenda.himno_set.values | himno:'4to'}}</p>
        <p><strong>Ultima Oracion:&nbsp;</strong> {{agenda.oracion_set.values | oracion:'final'}}</p>
        <div style="break-inside: avoid;">
          <! Se debe agregar lo siguiente para hacer un corte de pagina para imprimir: page-break-before: always>  
          <p><strong>Anuncios</strong></p>
          <ul>
            {% if agenda.actividad_set.values|length > 0 %}
              {% for anuncio in agenda.actividad_set.all %}
                <li class="with-bullet"><strong>{{anuncio.titulo}}</strong> ({{anuncio.organizacion}}) <i>{{anuncio.fecha|date:"l j F P"}}</i> - {{anuncio.descripcion}}</li>
              {% endfor %}
            {% endif %}
          {% if agenda.limpieza_set.values|length > 0 %}
            {% for limpieza in agenda.limpieza_set.all %}
              <li class="with-bullet"><strong>Limpieza:&nbsp;</strong>- {{limpieza.organizacion}} tiene asignada la limpieza esta semana
              </li>
            {% endfor %}
          {% endif %}
          <p><span class="divider"></span></p>
          <p><span class="divider"></span></p>
        </ul>
      </div>
    </main>
  {% else %}
    <h2>No hay agenda para la fecha seleccionada</h2>
  {% endif %}
</body>
<script>
  let size = {
    default: {
      header: "1.5em",
      sub_header: "1.17em",
      text: "1em"
    }, 
    medium: {
      header: "1.60em",
      sub_header: "1.27em",
      text: "1.10em"
    }, 
    large: {
      header: "1.70em",
      sub_header: "1.37em",
      text: "1.20em"
    }
  }
  document.querySelector("#font_size").addEventListener("change", (e) => {
    const value = e.target.value
    document.documentElement.style.setProperty("--header", size[value].header)
    document.documentElement.style.setProperty("--sub_header", size[value].sub_header)
    document.documentElement.style.setProperty("--text", size[value].text)
  })
  
</script>
</html>

api/templates/api/discurso.html
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>carta discurso</title>
  <style>
    body {
      margin: 0;
      padding: 0;
      height: 100vh;
      display: flex;
      flex-direction: column;
      justify-content: center;
      gap: 8em;
    }
    p {
      font-size: 1.25em;
    }

    .body {
      text-indent: 2em;
    }

    .fecha_carta {
      text-align: right;
    }

    #logo {
      position: absolute;
      top: 0;
      height: 150px;

    }

  </style>
  <script>
    const fecha = () => {
      let date = new Date()
      document.querySelector(".fecha_carta").innerHTML = `Guatemala, ${date.toLocaleDateString('es-GT', {year: 'numeric', month: 'long', day: 'numeric',})}`
    }
  </script>
</head>
<body onLoad="fecha();print();">
  <div>
    <p class="fecha_carta"></p>
    <br />
    <p>Estimado(a) hermano(a) <span class="nombre_hermano">{{discursante.nombre}}</span></p>
  </div>
  <div>
    <p class="body">Deseándole bendiciones sobre usted y su familia, reciba un cordial 
      saludo de parte del obispado del barrio Pinares 1. El motivo de esta 
      carta es para asignarle como discursante para la Reunión sacramental 
      del domingo <strong class="fecha_discurso">{{discursante.agenda.fecha}}</strong>. El tema es: <strong>{{discursante.tema}}</strong>. Tendrá un tiempo estimado de 10 a 
      12 minutos. Con la ayuda de las escrituras y la oración esperamos que 
      se pueda preparar para que el Espiritu le guíe y pueda edificar a los participantes de la reunion sacramental.
    </p>
    <p>
      De antemano agradecemos su disposición de servir al Señor, atentamente
    </p>
  </div>
  <p>
    Obispado Barrio Pinares 1
  </p>
</body>
</html>

api/templates/api/home.html
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="{% static 'fullcalendar/js/index.global.min.js' %}" defer></script>
  <title>Actividades</title>
  <style>
    body {
      margin: 0;
      pading: 0;
    }
    * {
      box-sizing: border-box;
    }

    main {
      max-width: 75%;
      margin: 0 auto;
    }

    .fc-toolbar-title {

      text-align: center;
    }
    
    @media (max-width: 800px) {
      main {
        max-width: 85%;
        margin: 0 auto;
      }
      .fc {
        font-size: .9em;
      }
    
      .fc-toolbar {
        flex-wrap: wrap;
      }
    
      .fc-toolbar-chunk:nth-child(2){
        order: -1;
        margin: 0 auto;
      }
      
    }
    
    @media (max-width: 799px) {
      main {
        max-width: 95%;
        margin: 0 auto;
      }
      .fc-toolbar {
        flex-direction: column;
      }
    }

    @media print {
      .fc-button-group {
        display: none !important;
      }

      .actions {
        display: none !important;
      }
    }

    #eventDialog::backDrop {
      background-color: rgba(0,0,0,0.7)
    }

    #eventDialog {
      border: none;
      border-radius: 10px;
      padding: 2em;
    }

    .actions {
      margin-top: 1em;
      display:flex;
      flex-direction: row;
      justify-content: space-between;
      align-items: center;
      gap: 1em;
    }

    .action {
      text-decoration: none;
      background-color: var(--fc-button-bg-color);
      border-color: var(--fc-button-border-color);
      color: var(--fc-button-text-color);
      padding: 0.4em 0.65em;
      border-radius: 0.25em;
      border: 1px solid transparent;
    }

    .action:hover {
      background-color: var(--fc-button-hover-bg-color);
    }

    .acciones {
      display: flex;
      flex-direction: row;
      justify-content: end;
    }

  </style>

</head>
<body>
  <main style="display: flex; flex-direction: column;">
    <section class="actions">
      <button class="action" onClick="window.print()">Imprimir</button>
      <a href="/admin" class="action">Ingresar</a>
    </section>
    <h1 style="margin: 0 auto;">Barrio Pianres 1</h1>
    <h2 style="margin: 0 auto;">Actividades</h2>
    <dialog id="eventDialog">
      <div class="detalles">
        <h2 id="eventTitle"></h2>
        <p>Organizacion: <span id="eventOrganizacion"></span></h3>
        <p id="eventDescripcion"></p>
        <p>Lugar: <span id="eventLugar"></span></p>
        <p>Fecha: <span id="eventFecha"></span></p>
        <p>Hora: <span id="eventHora"></span></p>
      </div>
      <div class="acciones">
        <button id="eventDialogclose" class="action">Cerrar</button>
      </div>
    </dialog>
    <div id="calendar"></div>
  </main>
  <script>
    const events = [
      {% for item in actividad %}
        {
          id: {{item.id}},
          title: "{{item.organizacion.nombre_corto}} - {{item.titulo}}",
          start: "{{item.fecha | date:'Y-m-d'}}T{{item.fecha | date:'H:i:s'}}",
          extendedProps: {
            tituloSimple: `{{item.titulo}}`,
            description: `{{item.descripcion}}`,
            fecha: "{{item.fecha | date:'l d F Y' }}",
            hora: "{{item.fecha | date:'h:i A'}}",
            lugar: "{{item.lugar}}",
            organizacion: "{{item.organizacion.nombre}}"
          }
        },
      {% endfor %}
    ]
    document.addEventListener('DOMContentLoaded', function() {
      let calendarEl = document.getElementById("calendar")
      let calendar = new FullCalendar.Calendar(calendarEl, {
        initialView: window.innerWidth < 768 ? 'listYear' : 'dayGridMonth',
        themeSystem: 'bootstrap5',
        locale: 'es',
        headerToolbar: {
          left: 'listYear,listMonth',
          center: 'title',
          right: 'prev,dayGridMonth,dayGridWeek,dayGridDay,next'
        },
        buttonText: {
          listYear: 'Lista por año',
          listMonth: 'Lista por mes',
          today: 'Hoy',
          month: 'Mes',
          week: 'Semana',
          day: 'Dia'
        },
        events: events,
        eventClick: function(info){
          console.log(info.event)
          showModal(info.event)
        }
      })
      calendar.render()
    })

    document.getElementById("eventDialogclose").addEventListener("click", () => {
      document.getElementById("eventDialog").close()
    })

    const showModal = (data) => {
      document.getElementById("eventTitle").innerText = data.extendedProps.tituloSimple
      document.getElementById("eventOrganizacion").innerText = data.extendedProps.organizacion
      document.getElementById("eventDescripcion").innerText = data.extendedProps.description
      document.getElementById("eventLugar").innerText = data.extendedProps.lugar
      document.getElementById("eventFecha").innerText = data.extendedProps.fecha
      document.getElementById("eventHora").innerText = data.extendedProps.hora
      document.getElementById("eventDialog").showModal()

    }
  </script>
  
</body>
</html>

api/templates/api/oracion.html
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title> - {{oracion.nombre}}</title>
  <style>
    body {
      margin: 0;
      padding: 0;
      height: 100vh;
      display: flex;
      flex-direction: column;
      justify-content: center;
      gap: 8em;
    }
    p {
      font-size: 1.25em;
    }

    .body {
      text-indent: 2em;
    }

    .fecha_carta {
      text-align: right;
    }

    #logo {
      position: absolute;
      top: 0;
      height: 150px;
    }

  </style>
  <script>
    const fecha = () => {
      let date = new Date()
      document.querySelector(".fecha_carta").innerHTML = `Guatemala, ${date.toLocaleDateString('es-GT', {year: 'numeric', month: 'long', day: 'numeric',})}`
    }
  </script>
</head>
<body onLoad="fecha();print();">
  <div>
    <p class="fecha_carta"></p>
    <p>Estimado(a) hermano(a) <span class="nombre_hermano">{{oracion.nombre}}</span></p>
  </div>
  <div>
    <p class="body">Deseándole bendiciones sobre usted y su familia, reciba un cordial saludo de parte del obispado del barrio Pinares 1. El motivo de esta carta es para asignarle la<strong> {{oracion.get_tipo_display}}</strong> para la Reunión sacramental del domingo <strong class="fecha_discurso">{{oracion.agenda.fecha}}</strong>. Rogamos su preparacion para dicha signacion con el fin de que la reunion sacramental pueda ser un momento espiritual edificante.
    </p>
    <p>
      De antemano agradecemos su disposición de servir al Señor, atentamente
    </p>
  </div>
  <p>
    Obispado Barrio Pinares 1
  </p>
</body>
</html>